### ISSUE TITLE
Initialize a Game

### ISSUE THREAD

**Issue by adirao-projects** [CSC207-2022F-UofT/course-project-chmess#1]
Creating a basic 8x8 chess board to start building more complicated systems.

**Comment by cherche** [comment]
There will be a method which creates a brand new Game instance. This is a multi-step process, involving creating instances of the Player class and Piece subclasses along the way. This is (almost) the only time Piece instances will ever be created, which isolates Piece constructor calls to the greatest extent possible. Code may be organized into smaller classes.

**Comment by cherche** [comment]
Not actually done. PR #15 only partially solves this, since `BoardCreator` hasn't been totally implemented yet
