### ISSUE TITLE
MovesGenerator class + subclasses for each Piece type

### ISSUE THREAD

**Issue by cherche** [CSC207-2022F-UofT/course-project-chmess#11]
- don't need to create a separate class file if MoveGenerator subclasses are small enough

edit: this is no longer relevant

**Comment by Gursach44** [comment]
Gurman is working on: Bishop, Rook, Queen MovesGens (long moving movers hehehahe)
David is working on: Knight, King, Pawn MovesGens

**Comment by cherche** [comment]
This issue shall also comprise the MovesGenerator class (what used to be #3)
