### ISSUE TITLE
CLIOutput class prevents program from compiling

### ISSUE THREAD

**Issue by cherche** [CSC207-2022F-UofT/course-project-chmess#27]
In the future, we should ensure new features come with tests (and documentation) so that the project (especially the main branch!) compiles. @adirao-projects let's work together on this, since David and I were the ones to finalize designs of the `Board` and `Piece` classes.

**Comment by adirao-projects** [comment]
@cherche are there any updated UMLs or class diagrams? The implementation for the CLI output class was dependent on those and I've just checked the updated files which have a completely different implementation then what was initially planned. If the current implementation is the one we're sticking with, we can delete the CLI Output class and completely redesign it.

**Comment by cherche** [comment]
No, there are no updated diagrams. We care discuss whether to maintain them tomorrow, but they may not be needed now that most classes are created and have their public methods.

The main thing that was preventing the program from compiling was some disagreeing type contracts and a typo on one of the first lines (`Class` instead of `class`). The CLIOutput class looks good; obviously you could not account for inconsistencies between the UML and the final design. It only needs some minor modifications.

My main point was that it should not have been committed to the `starter-code` branch.

**Comment by cherche** [comment]
@adirao-projects This urgent issue can be resolved by bypassing to immediately delete CLIOutput. (The class will still be available to be re-merged from your branch in #28.) This is something to discuss with the team.

**Comment by cherche** [comment]
This is resolved by #33 (1a2569e). The main branch now compiles, as one may verify from the GitHub autograding check.
